# 生成数组
可以用list，但为了方便使用，要转化为np数组

In [5]:
import numpy as np
x=list(range(10,29))
x

[10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28]

In [6]:
x=np.array(x)
x

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28])

In [7]:
e=np.random.randn(19)#表示19个数字
e

array([-0.01025067,  0.44296111,  0.56179025,  0.03440021,  0.54683412,
        0.41522241, -1.26142373,  0.42943446,  3.00484976, -1.29593588,
        1.019165  , -0.34590112,  1.50921146,  1.90195662, -1.42991753,
        0.38851598, -0.58190778,  0.44113513,  1.14354155])

In [8]:
x+e

array([ 9.98974933, 11.44296111, 12.56179025, 13.03440021, 14.54683412,
       15.41522241, 14.73857627, 17.42943446, 21.00484976, 17.70406412,
       21.019165  , 20.65409888, 23.50921146, 24.90195662, 22.57008247,
       25.38851598, 25.41809222, 27.44113513, 29.14354155])

定义一个随机生成的函数


In [9]:
import pandas as pd
def generate_data():
    """
    随机生成数据
    """
    #规定种子
    np.random.seed(4889)

    x=np.array([10]+list(range(10,29)))
    error=np.round(np.random.randn(20),2)#np.round表示四舍五入一个数组，第一个参数表示数组，第二个参数表示保留的小数位数
    y=x+error
    return pd.DataFrame({"x":x,"y":y})#放入字典，生成一个数据框

In [10]:
z=generate_data()
z

,x,y
0,10,7.70
1,10,9.87
2,11,11.18
3,12,10.43
4,13,12.36
5,14,14.15
6,15,15.73
7,16,16.40
8,17,18.86
9,18,16.13


提取x和y

In [11]:
z.y

0      7.70
1      9.87
2     11.18
3     10.43
4     12.36
5     14.15
6     15.73
7     16.40
8     18.86
9     16.13
10    18.21
11    18.37
12    22.61
13    19.83
14    22.67
15    22.70
16    25.16
17    25.55
18    28.21
19    28.12
Name: y, dtype: float64

# 数据可视化

In [12]:
import matplotlib.pyplot as plt #用于画画的

In [13]:
def visualize_data(data):
    """
    数据可视化
    """
    fig = plt.figure(figsize=(6,6),dpi=80) #设定图形框大小和分辨率
    ax = fig.add_subplot(111)# 设置只画一幅图，表示画布分成一行一列的第一幅图，这是缩写，参数为(rows=1,cols=1,index=1)
    # 设置标签名和刻度，range中表示每个刻度的位置，从10到30步长为5
    ax.set_xlabel("$x$")
    ax.set_xticks(range(10,31,5))
    ax.set_ylabel("$y$")
    ax.set_yticks(range(10,31,5))
    # 画点图，颜色为蓝色，label是图示
    ax.scatter(data.x,data.y,color="b",label=r"$y=x + \epsilon$")
    plt.legend(shadow=True)# 展示label内容
    plt.show()# 展示图形

    

In [15]:
import os
if __name__ == "__main__":
    data = generate_data()
    home_path = os.path.dirname(os.path.abspath(__file__))
    # 粗出数据，win和linux不同
    if os.name == "nt":
        data.to_csv("%s\\simple_example.csv" % home_path, index=False)#win
    else:
        data.to_csv("%s/simple_example.csv" % home_path, index=False)#linux
    visualize_data(data)

NameError: name '__file__' is not defined

# 线性模型实现

In [ ]:
path = "./simple_xeample.csv"
data = pd.read_csv(path)
data